### ISSUE TITLE
无法打开文件夹：双击webdav中的文件夹，播放器直接打开了

### ISSUE THREAD

**Issue by IMZCC** [Garefield/stellar-WebDAVClient#1]
无法打开文件夹：双击webdav中的文件夹，播放器直接打开了
![pic](https://user-images.githubusercontent.com/25655983/134631092-f7839b5b-42ea-4600-97ef-eeb75f7f19fa.png)

**Comment by IMZCC** [comment]
无法打开文件夹：双击webdav中的文件夹，播放器直接打开了
![image](https://user-images.githubusercontent.com/25655983/134631092-f7839b5b-42ea-4600-97ef-eeb75f7f19fa.png)

**Comment by Garefield** [comment]
应该是文件和文件夹的区分出问题了，我看看怎么解决
